" Vim syntax file for telic (.telic)
" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.
" Relies on the broad 'iskeyword' set below so punctuation words (+, ~, >r,
" @i,j, has?, kebab-case) match as keywords.

if exists("b:current_syntax")
  finish
endif

syn case match
syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58,60-64,94,126

syn sync fromstart

syn match   telicComment "\%(^\|\s\)\zs\\\%(\s.*\)\=$" contains=@Spell
syn region  telicString start=+"+ skip=+""+ end=+"+ contains=@Spell,telicFormat
syn match   telicFormat "{\d\+\%(:[^}]*\)\=}" contained
syn match   telicNumber "\<-\=\d\+\%(\.\d\+\)\=\%([eE][-+]\=\d\+\)\=\>"
syn match   telicSymbol  ":\k\+"
syn match   telicPath    "/\a\k*"
syn match   telicFrameOp  "[@!]\ze\k"
syn match   telicFrameKey "[@!]\@<=\k\+"

syn keyword telicDefine : variable constant symbol to forget inline internal ' lookup
syn match   telicDefine ";"
syn match   telicDefine "("
syn match   telicDefine ")"
syn match   telicDefName "\%(^\|\s\):\s\+\zs\k\+"
syn match   telicEffect  "\%(\%(^\|\s\):\s\+\k\+\s\+\)\@<=(\s[^)]*)\="

syn keyword telicConditional if ?if else then
syn keyword telicRepeat begin until again while repeat leave continue times i-times
syn keyword telicKeyword exit execute

syn keyword telicLogic lvar unify ~ deref $ amb fail _
syn keyword telicBoolean null

syn match   telicDelimiter "[][{}]"
syn match   telicDelimiter "\%(^\|\s\)\zs[<>]\ze\%(\s\|$\)"
syn match   telicDelimiter "\[<"
syn match   telicDelimiter ">\]"
syn match   telicDelimiter "\%(^\|\s\)\zs|\ze\%(\s\|$\)"

syn keyword telicBuiltin +! -! *! /! ++ -- f++ f-- f1+ f1- f+ f-
syn keyword telicBuiltin f* f/ f^ 1+ 1- 0= + - * / % ^
syn keyword telicBuiltin = <= >= f= f< f> f<= f>= !i ! @i,j @i
syn keyword telicBuiltin @j @ >r >side side> 2dup .s .a . !e !i,j ,
syn keyword telicBuiltin -rot 0-matrix 1= 2curry 2drop ? @e @or C E G H
syn keyword telicBuiltin HBAR KB NA PHI PI QE TAU abs acos add-last! advance-sprite after-entry
syn keyword telicBuiltin aggregate all? alloc-stats amplitude-at amplitude-spectrum and animation-finished? any? append-file apropos arg argmax
syn keyword telicBuiltin argmin args argsort array array-of array>frame array>set array? art>bitmap as as-column asin
syn keyword telicBuiltin assoc atan atan2 auc audio-off audio-on augment base basename between? binary-dir binomial-deviance
syn keyword telicBuiltin bit-and bit-not bit-or bit-xor blank-bitmap blit bootstrap bootstrap-with brier bye byte-size byte-substring
syn keyword telicBuiltin byte-vector>string bytes>value callers capture-bitmap case cat catch cd cfft char-at choose ci
syn keyword telicBuiltin circle clamp clear close cls codepoint-at codepoint>char codepoints>string colliding-sprites colors column-maxes column-means
syn keyword telicBuiltin column-mins column-sums column-type column>array column>set complete-cases complete-rows complex complex? compose concat conjugate
syn keyword telicBuiltin continuation? copy copy-file cor correlate-with correlation-kendall correlation-pearson correlation-spearman cos cosh count covariance
syn keyword telicBuiltin cp cr cross-validate cumulative-sum curry cv-folds cwd dataset>matrix dataset>rows date-shift date>epoch date>epoch-local
syn keyword telicBuiltin days-in-month db-close db-exec db-open db-query db? defer delete-at delete-directory delete-file denominator depth
syn keyword telicBuiltin diagonal diagonal-matrix difference dim do dot draw-bitmap draw-sprite draw-sprites drop drop-nans dup
syn keyword telicBuiltin each ecdf edit edit-distance effect! embodies embodies! emit end-process endcase endof ensure
syn keyword telicBuiltin env env! epoch>date epoch>date-local eq erf erfc evaluate exact>float exact? exp expand-grid
syn keyword telicBuiltin expect expect-near expect-throws expect= f*+ f*- fabs facos false false? fasin fatan
syn keyword telicBuiltin fcos fexp ffi-free ffi-function ffi-open ffi-variadic fft file-exists? file-info fill-circle fill-rect filter
syn keyword telicBuiltin filter-columns find-executable find-first first flat-map flatten fln fln1+ float>exact float? floats>matrix flog
syn keyword telicBuiltin fmod fnegate fold-times forget-instrument format format-time format-time-local frame frame>array frame>json frame? frames>dataset
syn keyword telicBuiltin frobenius-norm fround fround-down fround-up fsin fsq fsqrt ftan ftanh ftruncate gauges gauges>rows
syn keyword telicBuiltin gc gen-each gen-take group-by group-indices halt hann has? head help histogram-table hstack
syn keyword telicBuiltin icfft identity identity-matrix ifft imaginary-part in? index-of ink instrument! instrument-patch! int-segment intersection
syn keyword telicBuiltin iota iqr iso>time join json>frame key-down? key-pressed? key-set keys ks-distance last lgamma
syn keyword telicBuiltin line list-directory ln ln1+ load load-library load-tsv load-value log log10 log2 loop
syn keyword telicBuiltin lower-case lowest-bit ls lshift lvar? magnitude magnitudes make-directory man map map-frame match
syn keyword telicBuiltin match-all matches? matmul matrix matrix-range matrix>array matrix>pointer matrix? max max2 mean median
syn keyword telicBuiltin member? merge merge-by mesh min min2 mkdir mod mv n-columns n-rows name!key
syn keyword telicBuiltin name@key nan? ncurry negate neq new-tests nhead nip nlast nmap nonmissing-count norm
syn keyword telicBuiltin not note-off note-on now null? num-cores num-elements numerator of on-tick open-app-window open-file
syn keyword telicBuiltin or oscillator! over pad-left pad-right paper parallel-run parse-time partition pbootstrap peek percentile
syn keyword telicBuiltin pfilter pfilter-ext pick pitch>hz pitch>midi play-animation play-samples plot pmap pmap-ext pmap-reduce pmap-reduce-ext
syn keyword telicBuiltin pnorm pointer-cell pointer-deref pointer-long pointer-string-at pointer>address position-of print print-at print-gauges print-stack product-times
syn keyword telicBuiltin ptr? pwd qnorm quantile quantiles quantity? query query-rows quotient r> r@ random
syn keyword telicBuiltin random-int random-normal range ranks rationalize read read-arrow read-available read-bitmap read-err read-file read-line
syn keyword telicBuiltin read-out read-tsv real-part recent-audio rect recurse reduce reify reload remove-last! rename-file rename-key!
syn keyword telicBuiltin render render-audio repeat-column! replace replace-where! resample resample-indices resample-indices-ext reset reshape rest resume
syn keyword telicBuiltin reverse rm rmdir roll rot rotate-bitmap rotate-bitmap-angle round round-down round-up row-at row-maxes
syn keyword telicBuiltin row-means row-mins row-sums rows>dataset rshift run run-result running? sample sample-with-replacement sample-without-replacement save
syn keyword telicBuiltin save-tsv save-value screen-effect screen-frame screen-frames screen-shader screen-size screen-zoom se second see see-compiled
syn keyword telicBuiltin see-compiled>string see-tree see-tree>string see>string seed segment>pointer segment? select-columns select-eq select-keys select-neq select-rows
syn keyword telicBuiltin select-values sequence-articulation sequence-chord sequence-end sequence-instrument sequence-note sequence-rest sequence-tempo sequence-velocity set set-add! set-remove!
syn keyword telicBuiltin set-unit! set>array set? sheet>bitmaps shift shift-with shuffle side-depth side-drop side-peek sigmoid silence-audio
syn keyword telicBuiltin sin sinh size skip sleep slice! solutions sort sort-by sort-rows sort-rows-descending spaces
syn keyword telicBuiltin split split-by spread sprite-bitmap sprite-box sprites-collide? sprites-overlap? sq sqrt start-generator start-process std
syn keyword telicBuiltin stderr stdin stdout stdout>string stop stream? string>byte-vector string>chars string>codepoints string>number string>symbol string?
syn keyword telicBuiltin submatrix substring successive-differences sum sum-times summary swap symbol? take take-solutions tan tanh
syn keyword telicBuiltin telic telic-version test test-report throw tick-every time>iso timed to-slice! touch touch-file trace
syn keyword telicBuiltin transpose trim true true? truncate try-catch tsv>db tty? tuck type-of typed-text unify?
syn keyword telicBuiltin union unit unit-of update-at upper-case value>bytes values var variables vars vector vf*
syn keyword telicBuiltin vf+ vf- vf/ vfabs vfcos vfexp vflog vfneg vfsin vfsq vfsqrt vftan
syn keyword telicBuiltin vftanh vstack vvf* vvf*+ vvf*- vvf+ vvf- vvf/ wait wait-audio wait-readable wait-sequence
syn keyword telicBuiltin wall-now where wildcard? with-db with-stream within-groups words write write-arrow write-bitmap write-file write-in
syn keyword telicBuiltin write-tsv xml-escape xt? yield zero-variance?

hi def link telicComment      Comment
hi def link telicString       String
hi def link telicNumber       Number
hi def link telicSymbol       Type
hi def link telicPath         Type
hi def link telicFrameOp      Operator
hi def link telicFrameKey     Type
hi def link telicDefine       Define
hi def link telicDefName      Function
hi def link telicEffect       Identifier
hi def link telicConditional  Conditional
hi def link telicRepeat       Repeat
hi def link telicKeyword      Keyword
hi def link telicLogic        Special
hi def link telicBoolean      Boolean
hi def link telicDelimiter    Delimiter
hi def link telicBuiltin      Statement
hi def link telicFormat       SpecialChar

let b:current_syntax = "telic"
