" Vim syntax file for telic (.telic)
" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.
" Relies on the broad 'iskeyword' set below so punctuation words (+, ~, >r,
" @i,j, has?, kebab-case) match as keywords.

if exists("b:current_syntax")
  finish
endif

syn case match
syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58,60-64,94,126

syn sync fromstart

syn match   telicComment "\%(^\|\s\)\zs\\\%(\s.*\)\=$" contains=@Spell
syn region  telicComment start="\[\@<!(\s" end=")" contains=@Spell
syn region  telicString start=+"+ skip=+""+ end=+"+ contains=@Spell,telicFormat
syn match   telicFormat "{\d\+\%(:[^}]*\)\=}" contained
syn match   telicNumber "\<-\=\d\+\%(\.\d\+\)\=\%([eE][-+]\=\d\+\)\=\>"
syn match   telicSymbol  ":\k\+"
syn match   telicPath    "/\a\k*"
syn match   telicFrameOp  "[@!]\ze\k"
syn match   telicFrameKey "[@!]\@<=\k\+"

syn keyword telicDefine : variable constant symbol to forget inline internal ' lookup
syn match   telicDefine ";"
syn match   telicDefine "\[:"
syn match   telicDefine ":\]"
syn match   telicDefName "\%(^\|\s\):\s\+\zs\k\+"

syn keyword telicConditional if ?if else then
syn keyword telicRepeat begin until again while repeat leave continue times i-times
syn keyword telicKeyword exit execute

syn keyword telicLogic lvar unify ~ deref $ amb fail _
syn keyword telicBoolean null

syn match   telicDelimiter "[][{}]"
syn match   telicDelimiter "\%(^\|\s\)\zs[<>]\ze\%(\s\|$\)"
syn match   telicDelimiter "\[("
syn match   telicDelimiter ")\]"
syn match   telicDelimiter "\[<"
syn match   telicDelimiter ">\]"
syn match   telicDelimiter "\%(^\|\s\)\zs|\ze\%(\s\|$\)"

syn keyword telicBuiltin +! -! *! /! ++ -- f++ f-- f1+ f1- f+ f-
syn keyword telicBuiltin f* f/ f^ 1+ 1- 0= + - * / % ^
syn keyword telicBuiltin = <= >= f= f< f> f<= f>= !i ! @i,j @i
syn keyword telicBuiltin @j @ >r >side side> 2dup .s .a . !e !i,j ,
syn keyword telicBuiltin -rot 0-matrix 1= 2curry 2drop ? @e @or C E G H
syn keyword telicBuiltin HBAR KB NA PHI PI QE TAU abs acos add-last! aggregate all?
syn keyword telicBuiltin alloc-stats and any? append-file apropos arg argmax argmin args argsort array array-of
syn keyword telicBuiltin array>cons array>frame array>set array? as as-column asin assert assoc atan atan2 auc
syn keyword telicBuiltin augment base basename between? binary-dir binomial-deviance bit-and bit-not bit-or bit-xor bootstrap bootstrap-with
syn keyword telicBuiltin brier bulk-load bye byte-size byte-substring bytes>value callers case cat catch cd char-at
syn keyword telicBuiltin choose ci clamp clear close codepoint-at codepoint>char codepoints>string column-maxes column-means column-mins column-sums
syn keyword telicBuiltin column-type column>array column>set complete-cases complete-rows complex complex? concat conjugate cons cons>array continuation?
syn keyword telicBuiltin copy copy-file cor correlate-with correlation-kendall correlation-pearson correlation-spearman cos cosh count count-matches covariance
syn keyword telicBuiltin cp cr create-index cross-validate cumulative-sum curry cv-folds cwd dataset>matrix dataset>rows date-shift date>epoch
syn keyword telicBuiltin date>epoch-local days-in-month db-close db-exec db-open db-query db-query>dataset db? defer delete-at delete-directory delete-file
syn keyword telicBuiltin denominator depth diagonal diagonal-matrix difference dim do dot double-segment drop drop-nans dup
syn keyword telicBuiltin each ecdf edit edit-distance embodies embodies! emit end-process endcase endof ensure env
syn keyword telicBuiltin env! epoch>date epoch>date-local eq erf erfc evaluate exact>float exact? exp expand-grid expect
syn keyword telicBuiltin expect-near expect-throws expect= f*+ f*- fabs facos false false? fasin fatan fcos
syn keyword telicBuiltin fexp ffi-free ffi-function ffi-open ffi-variadic file-exists? file-info filter filter-columns find-executable find-first first
syn keyword telicBuiltin flat-map flatten flatten-array fln fln1+ float>exact float? floats>matrix flog fmod fnegate fold-times
syn keyword telicBuiltin format format-time format-time-local frame frame>array frame>json frame? frames>dataset frobenius-norm fround fround-down fround-up
syn keyword telicBuiltin fsin fsq fsqrt ftan ftanh ftruncate gauges gc gen-each gen-take group-by group-indices
syn keyword telicBuiltin group-with halt has? head head-tail headn help histogram-table hstack identity identity-matrix imaginary-part
syn keyword telicBuiltin in? index-of inner-join int-segment intersection iota iqr iso>time join json>frame key-set keys
syn keyword telicBuiltin ks-distance last lgamma list-directory ln ln1+ load load-bag load-library load-tsv load-value log
syn keyword telicBuiltin log10 log2 loop lower-case lowest-bit ls lshift lvar? magnitude make-directory man map
syn keyword telicBuiltin match match-all matches? matmul matrix matrix-range matrix>array matrix>pointer matrix? max max2 mean
syn keyword telicBuiltin median merge merge-by mesh min min2 mkdir mod mv n-columns n-rows name!key
syn keyword telicBuiltin name@key nan? ncurry negate neq new-tests nip nlast nmap nonmissing-count norm not
syn keyword telicBuiltin now null? num-cores num-elements numerator of open-app-window open-file or over pad-left pad-right
syn keyword telicBuiltin pair? parallel-run parse-time partition pbootstrap peek percentile pfilter pfilter-ext pick pmap pmap-ext
syn keyword telicBuiltin pmap-reduce pmap-reduce-ext pnorm pointer-cell pointer-deref pointer-long pointer-string-at pointer>address print print-gauges print-stack product-times
syn keyword telicBuiltin ptr? pwd qnorm quantile quantiles quantity? query quotient r> r@ random random-int
syn keyword telicBuiltin random-normal range ranks rationalize read read-available read-err read-file read-line read-out read-tsv real-part
syn keyword telicBuiltin recurse reduce reify relation reload remove-last! rename-file rename-key! render repeat-column! replace replace-where!
syn keyword telicBuiltin resample resample-indices resample-indices-ext reset reshape resume retract reverse rm rmdir roll rot
syn keyword telicBuiltin round round-down round-up row-at row-maxes row-means row-mins row-sums rows>dataset rows>relation rshift run
syn keyword telicBuiltin run-result running? sample sample-with-replacement sample-without-replacement save save-tsv save-value se second see see-compiled
syn keyword telicBuiltin see-compiled>string see-tree see-tree>string see>string seed segment>pointer segment? select-columns select-eq select-keys select-neq select-rows
syn keyword telicBuiltin select-values set set-add! set-remove! set-unit! set>array set? shift shift-with shuffle side-depth side-drop
syn keyword telicBuiltin side-peek sigmoid sin sinh size skip sleep slice! solutions sort sort-by sort-rows
syn keyword telicBuiltin sort-rows-descending spaces split split-by spread sq sqrt start-generator start-process std stderr stdin
syn keyword telicBuiltin stdout stdout>string stop stream? string>chars string>codepoints string>number string>symbol string? submatrix substring successive-differences
syn keyword telicBuiltin sum sum-times summary swap symbol? take take-solutions tan tanh telic telic-version test
syn keyword telicBuiltin test-report throw time>iso timed to-slice! touch touch-file trace transpose trim true true?
syn keyword telicBuiltin truncate try-catch tsv>db tty? tuck type-of unify? union unit unit-of update-at upper-case
syn keyword telicBuiltin value>bytes values var variables vars vector vf* vf+ vf- vf/ vfabs vfcos
syn keyword telicBuiltin vfexp vflog vfneg vfsin vfsq vfsqrt vftan vftanh vstack vvf* vvf*+ vvf*-
syn keyword telicBuiltin vvf+ vvf- vvf/ wait wait-readable wall-now where wildcard? with-db with-stream within-groups words
syn keyword telicBuiltin write write-file write-in write-tsv xml-escape xt? yield zero-variance?

hi def link telicComment      Comment
hi def link telicString       String
hi def link telicNumber       Number
hi def link telicSymbol       Constant
hi def link telicPath         Constant
hi def link telicFrameOp      Operator
hi def link telicFrameKey     Type
hi def link telicDefine       Define
hi def link telicDefName      Function
hi def link telicConditional  Conditional
hi def link telicRepeat       Repeat
hi def link telicKeyword      Keyword
hi def link telicLogic        Special
hi def link telicBoolean      Boolean
hi def link telicDelimiter    Delimiter
hi def link telicBuiltin      Statement
hi def link telicFormat       SpecialChar

let b:current_syntax = "telic"
