" Vim syntax file for telic (.telic)
" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.
" Relies on the broad 'iskeyword' set below so punctuation words (+, ~, >r,
" @i,j, has?, kebab-case) match as keywords.

if exists("b:current_syntax")
  finish
endif

syn case match
syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58,60-64,94,126

syn sync fromstart

syn match   telicComment "\%(^\|\s\)\zs\\\%(\s.*\)\=$" contains=@Spell
syn region  telicComment start="\[\@<!(\s" end=")" contains=@Spell
syn region  telicString start=+"+ skip=+""+ end=+"+ contains=@Spell,telicFormat
syn match   telicFormat "{\d\+\%(:[^}]*\)\=}" contained
syn match   telicNumber "\<-\=\d\+\%(\.\d\+\)\=\%([eE][-+]\=\d\+\)\=\>"
syn match   telicSymbol  ":\k\+"
syn match   telicPath    "/\a\k*"
syn match   telicFrameOp  "[@!]\ze\k"
syn match   telicFrameKey "[@!]\@<=\k\+"

syn keyword telicDefine : variable constant symbol to forget inline internal ' lookup
syn match   telicDefine ";"
syn match   telicDefine "\[:"
syn match   telicDefine ":\]"
syn match   telicDefName "\%(^\|\s\):\s\+\zs\k\+"

syn keyword telicConditional if ?if else then
syn keyword telicRepeat begin until again while repeat leave continue times i-times
syn keyword telicKeyword exit execute

syn keyword telicLogic lvar unify ~ deref $ amb fail _
syn keyword telicBoolean null

syn match   telicDelimiter "[][{}]"
syn match   telicDelimiter "\%(^\|\s\)\zs[<>]\ze\%(\s\|$\)"
syn match   telicDelimiter "\[("
syn match   telicDelimiter ")\]"
syn match   telicDelimiter "\[<"
syn match   telicDelimiter ">\]"
syn match   telicDelimiter "\%(^\|\s\)\zs|\ze\%(\s\|$\)"

syn keyword telicBuiltin +! -! *! /! ++ -- f++ f-- f1+ f1- f+ f-
syn keyword telicBuiltin f* f/ f^ 1+ 1- 0= + - * / % ^
syn keyword telicBuiltin = <= >= f= f< f> f<= f>= !i ! @i,j @i
syn keyword telicBuiltin @j @ >r >side side> 2dup .s .a . !e !i,j ,
syn keyword telicBuiltin -rot 0-matrix 1= 2curry 2drop ? @e @or C E G H
syn keyword telicBuiltin HBAR KB NA PHI PI QE TAU abs acos add-last! aggregate all?
syn keyword telicBuiltin alloc-stats and any? append-file apropos arg argmax argmin args argsort array array-of
syn keyword telicBuiltin array>cons array>frame array>set array? as as-column asin assert atan atan2 auc augment
syn keyword telicBuiltin base basename between? binary-dir binomial-deviance bit-and bit-not bit-or bit-xor bootstrap bootstrap-with brier
syn keyword telicBuiltin bulk-load bye byte-size byte-substring bytes>value callers case cat catch cd char-at choose
syn keyword telicBuiltin ci clamp clear close codepoint-at codepoint>char codepoints>string column-maxes column-means column-mins column-sums column-type
syn keyword telicBuiltin column>array column>set complete-cases complete-rows complex complex? concat conjugate cons cons>array continuation? copy
syn keyword telicBuiltin copy-file cor correlate-with correlation-kendall correlation-pearson correlation-spearman cos cosh count count-matches covariance cp
syn keyword telicBuiltin cr create-index cross-validate cumulative-sum curry cv-folds cwd dataset>matrix dataset>rows date-shift date>epoch date>epoch-local
syn keyword telicBuiltin days-in-month db-close db-exec db-open db-query db-query>dataset db? defer delete-at delete-directory delete-file denominator
syn keyword telicBuiltin depth diagonal diagonal-matrix difference dim do dot double-segment drop drop-nans dup each
syn keyword telicBuiltin ecdf edit edit-distance embodies embodies! emit end-process endcase endof ensure env env!
syn keyword telicBuiltin epoch>date epoch>date-local eq erf erfc evaluate exact>float exact? exp expand-grid expect expect-near
syn keyword telicBuiltin expect-throws expect= f*+ f*- fabs facos false false? fasin fatan fcos fexp
syn keyword telicBuiltin ffi-free ffi-function ffi-open ffi-variadic file-exists? file-info filter filter-columns find-executable find-first first flat-map
syn keyword telicBuiltin flatten flatten-array fln fln1+ float>exact float? floats>matrix flog fmod fnegate fold-times format
syn keyword telicBuiltin format-time format-time-local frame frame>array frame>json frame? frames>dataset frobenius-norm fround fround-down fround-up fsin
syn keyword telicBuiltin fsq fsqrt ftan ftanh ftruncate gauges gc gen-each gen-take group-by group-indices group-with
syn keyword telicBuiltin halt has? head head-tail headn help histogram-table hstack identity identity-matrix imaginary-part in?
syn keyword telicBuiltin index-of inner-join int-segment intersection iota iqr iso>time join json>frame key-set keys ks-distance
syn keyword telicBuiltin last lgamma list-directory ln ln1+ load load-bag load-library load-tsv load-value log log10
syn keyword telicBuiltin log2 loop lower-case lowest-bit ls lshift lvar? magnitude make-directory man map match
syn keyword telicBuiltin match-all matches? matmul matrix matrix-range matrix>array matrix>pointer matrix? max max2 mean median
syn keyword telicBuiltin merge merge-by mesh min min2 mkdir mod mv n-columns n-rows name!key name@key
syn keyword telicBuiltin nan? ncurry negate neq new-tests nip nlast nmap none? nonmissing-count norm not
syn keyword telicBuiltin now num-cores num-elements numerator of open-app-window open-file or over pad-left pad-right pair?
syn keyword telicBuiltin parallel-run parse-time partition pbootstrap peek percentile pfilter pfilter-ext pick pmap pmap-ext pmap-reduce
syn keyword telicBuiltin pmap-reduce-ext pnorm pointer-cell pointer-deref pointer-long pointer-string-at pointer>address print print-gauges print-stack product-times ptr?
syn keyword telicBuiltin pwd qnorm quantile quantiles quantity? query quotient r> r@ random random-int random-normal
syn keyword telicBuiltin range ranks rationalize read read-available read-err read-file read-line read-out read-tsv real-part recurse
syn keyword telicBuiltin reduce reify relation reload remove-last! rename-file rename-key! render replace replace-where! resample resample-indices
syn keyword telicBuiltin resample-indices-ext reset reshape resume retract reverse rm rmdir roll rot round round-down
syn keyword telicBuiltin round-up row-at row-maxes row-means row-mins row-sums rows>dataset rows>relation rshift run run-result running?
syn keyword telicBuiltin sample sample-with-replacement sample-without-replacement save save-tsv save-value se second see see-compiled see-compiled>string see-tree
syn keyword telicBuiltin see-tree>string see>string seed segment>pointer segment? select-columns select-eq select-keys select-neq select-rows select-values set
syn keyword telicBuiltin set-add! set-remove! set-unit! set>array set? shift shift-with shuffle side-depth side-drop side-peek sigmoid
syn keyword telicBuiltin sin sinh size skip sleep slice! solutions sort sort-by sort-rows sort-rows-descending spaces
syn keyword telicBuiltin split spread sq sqrt start-generator start-process std stderr stdin stdout stdout>string stop
syn keyword telicBuiltin stream? string>chars string>codepoints string>number string>symbol string? submatrix substring successive-differences sum sum-times summary
syn keyword telicBuiltin swap symbol? take take-solutions tan tanh telic telic-version test test-report throw time>iso
syn keyword telicBuiltin timed to-slice! touch touch-file trace transpose trim true true? truncate try-catch tsv>db
syn keyword telicBuiltin tty? tuck type-of unify? union unit unit-of update-at upper-case value>bytes values var
syn keyword telicBuiltin variables vars vector vf* vf+ vf- vf/ vfabs vfcos vfexp vflog vfneg
syn keyword telicBuiltin vfsin vfsq vfsqrt vftan vftanh vstack vvf* vvf*+ vvf*- vvf+ vvf- vvf/
syn keyword telicBuiltin wait wait-readable wall-now where wildcard? with-db with-stream words write write-file write-in write-tsv
syn keyword telicBuiltin xml-escape xt? yield

hi def link telicComment      Comment
hi def link telicString       String
hi def link telicNumber       Number
hi def link telicSymbol       Constant
hi def link telicPath         Constant
hi def link telicFrameOp      Operator
hi def link telicFrameKey     Type
hi def link telicDefine       Define
hi def link telicDefName      Function
hi def link telicConditional  Conditional
hi def link telicRepeat       Repeat
hi def link telicKeyword      Keyword
hi def link telicLogic        Special
hi def link telicBoolean      Boolean
hi def link telicDelimiter    Delimiter
hi def link telicBuiltin      Statement
hi def link telicFormat       SpecialChar

let b:current_syntax = "telic"
