" Vim syntax file for water (.h2o)
" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.
" Relies on the broad 'iskeyword' set below so punctuation words (+, ~, >r,
" @i,j, has?, kebab-case) match as keywords.

if exists("b:current_syntax")
  finish
endif

syn case match
syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58,60-64,94,126

syn match   waterComment "\%(^\|\s\)\zs\\\%(\s.*\)\=$" contains=@Spell
syn region  waterComment start="\[\@<!(\s" end=")" contains=@Spell
syn region  waterString start=+"+ skip=+""+ end=+"+ contains=@Spell,waterFormat
syn match   waterFormat "{\d\+\%(:[^}]*\)\=}" contained
syn match   waterNumber "\<-\=\d\+\%(\.\d\+\)\=\%([eE][-+]\=\d\+\)\=\>"
syn match   waterSymbol  ":\k\+"
syn match   waterPath    "/\a\k*"
syn match   waterFrameOp  "[@!]\ze\k"
syn match   waterFrameKey "[@!]\@<=\k\+"

syn keyword waterDefine : variable constant symbol to forget inline internal ' lookup
syn match   waterDefine ";"
syn match   waterDefine "\[:"
syn match   waterDefine "\[|"
syn match   waterDefine "\[>"
syn match   waterDefine ":\]"
syn match   waterDefName "\%(^\|\s\):\s\+\zs\k\+"

syn keyword waterConditional if ?if else then
syn keyword waterRepeat begin until again while repeat leave continue times i-times
syn keyword waterKeyword exit execute

syn keyword waterLogic lvar unify ~ deref $ amb fail _
syn keyword waterBoolean null

syn match   waterDelimiter "[][{}]"
syn match   waterDelimiter "\%(^\|\s\)\zs[<>]\ze\%(\s\|$\)"
syn match   waterDelimiter "\[("
syn match   waterDelimiter ")\]"
syn match   waterDelimiter "\[<"
syn match   waterDelimiter ">\]"
syn match   waterDelimiter "\%(^\|\s\)\zs|>\=\ze\%(\s\|$\)"

syn keyword waterBuiltin +! -! *! /! ++ -- f++ f-- f1+ f1- f+ f-
syn keyword waterBuiltin f* f/ f^ 1+ 1- 0= + - * / % ^
syn keyword waterBuiltin = <= >= f= f< f> f<= f>= !i ! @i,j @i
syn keyword waterBuiltin @j @ >r >side side> 2dup .s .a . !at !e !i,j
syn keyword waterBuiltin , -rot 0-matrix 1= 2curry 2drop ? @e @or C E G
syn keyword waterBuiltin H HBAR KB NA PHI PI QE TAU abs acos add-last! all?
syn keyword waterBuiltin alloc-stats and any? append-file apropos argmax argmin argsort array array-of array>cons array>frame
syn keyword waterBuiltin array>set array? as-column asin assert atan auc augment base basename binary-dir binomial-deviance
syn keyword waterBuiltin bit-and bit-not bit-or bit-xor bootstrap bootstrap-with brier bulk-load bye byte-size byte-substring catch
syn keyword waterBuiltin cd char-at choose ci clear close codepoint-at codepoint>char codepoints>string column-maxes column-means column-mins
syn keyword waterBuiltin column-sums column-type column>array column>indicators column>set complete-cases concat cons cons>array continuation? copy cor
syn keyword waterBuiltin correlate-with correlation-kendall correlation-pearson correlation-spearman cos count count-matches cr create-index cross-validate cumulative-sum curry
syn keyword waterBuiltin cv-folds cwd dataset>matrix dataset>rows date-shift date>epoch date>epoch-local days-in-month db-close db-exec db-open db-query
syn keyword waterBuiltin db-query>dataset db? defer delete-at depth destruct destruct-to dgemm-nn dgemm-nt dgemm-tn dgemm-tt diagonal
syn keyword waterBuiltin diagonal-matrix difference dim dot double-segment draw-node draw-tree drop drop-nans dup each ecdf
syn keyword waterBuiltin edit-distance embodies embodies! emit end-process ensure env env! epoch>date epoch>date-local eq exp
syn keyword waterBuiltin expect expect-near expect-throws expect= f*+ f*- fabs facos false fasin fatan fcos
syn keyword waterBuiltin feature-importance fexp ffi-free ffi-function ffi-open ffi-variadic file-exists? filter find-executable find-first first fit-tree
syn keyword waterBuiltin flat-map flatten flatten-array fln float? floats>matrix flog fmod fnegate format format-time format-time-local
syn keyword waterBuiltin frame frame>array frame>json frame? frames>dataset frobenius-norm fround fround-down fround-up fsin fsq fsqrt
syn keyword waterBuiltin ftan ftanh ftruncate gc gen-each gen-take group-by group-indices group-with has? head head-tail
syn keyword waterBuiltin headn help histogram-table hstack identity identity-matrix index-of indicators! inner-join int-segment intersection iota
syn keyword waterBuiltin iqr iso>time join json>frame keys ks-distance last lgamma ln load load-bag load-image
syn keyword waterBuiltin load-library load-tsv log lowest-bit lshift lvar? magnitude man map match match-all matches?
syn keyword waterBuiltin matrix matrix-range matrix>array matrix>pointer matrix? max max2 mean median member? merge mesh
syn keyword waterBuiltin min min2 mod n-columns n-observations n-rows name!key name@key nan? ncurry negate new-tests
syn keyword waterBuiltin nip nmap none? nonmissing-count norm not now num-cores num-elements open-app-window or over
syn keyword waterBuiltin pad-left pad-right pair? parallel-run parse-time partition pbootstrap peek percentile pfilter pfilter-ext pfit-tree
syn keyword waterBuiltin pick pmap pmap-ext pmap-reduce pmap-reduce-ext pointer-cell pointer-deref pointer-long pointer-string-at pointer>address predict print
syn keyword waterBuiltin print-stack prune prune-cv ptr? qnorm quantile quantiles quantity? query quotient r> r@
syn keyword waterBuiltin random random-int range ranks read read-err read-file read-out read-tsv recurse reduce regress-with
syn keyword waterBuiltin reify relation reload remove-last! render replace replace-where resample resample-indices resample-indices-ext reset reshape
syn keyword waterBuiltin resume retract reverse roll rot round round-down round-up row-maxes row-means row-mins row-sums
syn keyword waterBuiltin rows>dataset rows>relation rshift run run-result running? sample sample-with-replacement sample-without-replacement save save-image save-tsv
syn keyword waterBuiltin se second see see-compiled see-compiled>string see-tree see-tree>string see>string seed segment>pointer segment? select-columns
syn keyword waterBuiltin select-keys select-rows select-values set set-add! set-remove! set>array set? shift shift-with shuffle side-depth
syn keyword waterBuiltin side-drop side-peek sigmoid sin size skip sleep slice! sort sort-by spaces split
syn keyword waterBuiltin sq sqrt start-generator start-process std stderr stdin stdout stop stream? string>chars string>codepoints
syn keyword waterBuiltin string>number string>symbol string? submatrix substring sum summary swap symbol? take tan tanh
syn keyword waterBuiltin test test-report that this throw time>iso timed to-slice! transpose trim true truncate
syn keyword waterBuiltin try-catch tsv>db type-of union unit unit-of update-at values var variables vars vector
syn keyword waterBuiltin vf* vf+ vf- vf/ vfabs vfcos vfexp vflog vfneg vfsin vfsq vfsqrt
syn keyword waterBuiltin vftan vftanh vstack vvf* vvf*+ vvf*- vvf+ vvf- vvf/ wait wall-now water
syn keyword waterBuiltin where wildcard? with-db with-intercept with-stream words write write-file write-in write-tsv xml-escape xt?
syn keyword waterBuiltin yield

hi def link waterComment      Comment
hi def link waterString       String
hi def link waterNumber       Number
hi def link waterSymbol       Constant
hi def link waterPath         Constant
hi def link waterFrameOp      Operator
hi def link waterFrameKey     Type
hi def link waterDefine       Define
hi def link waterDefName      Function
hi def link waterConditional  Conditional
hi def link waterRepeat       Repeat
hi def link waterKeyword      Keyword
hi def link waterLogic        Special
hi def link waterBoolean      Boolean
hi def link waterDelimiter    Delimiter
hi def link waterBuiltin      Statement
hi def link waterFormat       SpecialChar

let b:current_syntax = "water"
