" Vim syntax file for water (.h2o)
" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.
" Relies on the broad 'iskeyword' set below so punctuation words (+, ~, >r,
" @i,j, has?, kebab-case) match as keywords.

if exists("b:current_syntax")
  finish
endif

syn case match
syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58,60-64,94,126

syn match   waterComment "\%(^\|\s\)\zs\\\%(\s.*\)\=$" contains=@Spell
syn region  waterComment start="\[\@<!(\s" end=")" contains=@Spell
syn region  waterString start=+"+ skip=+""+ end=+"+ contains=@Spell,waterFormat
syn match   waterFormat "{\d\+\%(:[^}]*\)\=}" contained
syn match   waterNumber "\<-\=\d\+\%(\.\d\+\)\=\%([eE][-+]\=\d\+\)\=\>"
syn match   waterSymbol  ":\k\+"
syn match   waterPath    "/\a\k*"
syn match   waterFrameOp  "[@!]\ze\k"
syn match   waterFrameKey "[@!]\@<=\k\+"

syn keyword waterDefine : variable constant symbol to forget inline internal ' lookup
syn match   waterDefine ";"
syn match   waterDefine "\[:"
syn match   waterDefine "\[|"
syn match   waterDefine "\[>"
syn match   waterDefine ":\]"
syn match   waterDefName "\%(^\|\s\):\s\+\zs\k\+"

syn keyword waterConditional if ?if else then
syn keyword waterRepeat begin until again while repeat leave continue times i-times
syn keyword waterKeyword exit execute

syn keyword waterLogic lvar unify ~ deref $ amb fail _
syn keyword waterBoolean null

syn match   waterDelimiter "[][{}]"
syn match   waterDelimiter "\%(^\|\s\)\zs[<>]\ze\%(\s\|$\)"
syn match   waterDelimiter "\[("
syn match   waterDelimiter ")\]"
syn match   waterDelimiter "\[<"
syn match   waterDelimiter ">\]"
syn match   waterDelimiter "\%(^\|\s\)\zs|>\=\ze\%(\s\|$\)"

syn keyword waterBuiltin +! -! *! /! ++ -- f++ f-- f1+ f1- f+ f-
syn keyword waterBuiltin f* f/ f^ 1+ 1- 0= + - * / % ^
syn keyword waterBuiltin = <= >= f= f< f> f<= f>= !i ! @i,j @i
syn keyword waterBuiltin @j @ >r >side side> 2dup .s .a . !e !i,j ,
syn keyword waterBuiltin -rot 0-matrix 1= 2curry 2drop ? @e @or C E G H
syn keyword waterBuiltin HBAR KB NA PHI PI QE TAU abs acos add-last! all? alloc-stats
syn keyword waterBuiltin and any? append-file apropos argmax argmin argsort array array-of array>cons array>frame array>set
syn keyword waterBuiltin array? as-column asin assert atan auc augment base basename binary-dir binomial-deviance bit-and
syn keyword waterBuiltin bit-not bit-or bit-xor bootstrap bootstrap-with brier bulk-load bye byte-size byte-substring catch cd
syn keyword waterBuiltin char-at choose ci clear close codepoint-at codepoint>char codepoints>string column-maxes column-means column-mins column-sums
syn keyword waterBuiltin column-type column>array column>indicators column>set complete-cases concat cons cons>array continuation? copy cor correlate-with
syn keyword waterBuiltin correlation-kendall correlation-pearson correlation-spearman cos count count-matches cr create-index cross-validate cumulative-sum curry cv-folds
syn keyword waterBuiltin cwd dataset>matrix dataset>rows date-shift date>epoch date>epoch-local days-in-month db-close db-exec db-open db-query db-query>dataset
syn keyword waterBuiltin db? defer delete-at depth destruct destruct-to dgemm-nn dgemm-nt dgemm-tn dgemm-tt diagonal diagonal-matrix
syn keyword waterBuiltin difference dim dot double-segment draw-node draw-tree drop drop-nans dup each ecdf edit-distance
syn keyword waterBuiltin embodies embodies! emit end-process ensure env env! epoch>date epoch>date-local eq exp expect
syn keyword waterBuiltin expect-near expect-throws expect= f*+ f*- fabs facos false fasin fatan fcos feature-importance
syn keyword waterBuiltin fexp ffi-free ffi-function ffi-open ffi-variadic file-exists? filter find-executable find-first first fit-tree flat-map
syn keyword waterBuiltin flatten flatten-array fln float? floats>matrix flog fmod fnegate format format-time format-time-local frame
syn keyword waterBuiltin frame>array frame>json frame? frames>dataset frobenius-norm fround fround-down fround-up fsin fsq fsqrt ftan
syn keyword waterBuiltin ftanh ftruncate gc gen-each gen-take group-by group-indices group-with has? head head-tail headn
syn keyword waterBuiltin help histogram-table hstack identity identity-matrix index-of indicators! inner-join int-segment intersection iota iqr
syn keyword waterBuiltin iso>time join json>frame keys ks-distance last lgamma ln load load-bag load-image load-library
syn keyword waterBuiltin load-tsv log lowest-bit lshift lvar? magnitude man map mapn match match-all matches?
syn keyword waterBuiltin matrix matrix-range matrix>array matrix>pointer matrix? max max2 mean median member? merge mesh
syn keyword waterBuiltin min min2 mod n-columns n-observations n-rows name!key name@key nan? negate new-tests nip
syn keyword waterBuiltin none? nonmissing-count norm not now num-cores num-elements open-app-window or over pad-left pad-right
syn keyword waterBuiltin pair? parallel-run parse-time partition pbootstrap peek percentile pfilter pfilter-ext pfit-tree pmap pmap-ext
syn keyword waterBuiltin pmap-reduce pmap-reduce-ext pointer-cell pointer-deref pointer-long pointer-string-at pointer>address predict print print-stack prune prune-cv
syn keyword waterBuiltin ptr? qnorm quantile quantiles quantity? query quotient r> r@ random random-int range
syn keyword waterBuiltin ranks read read-err read-file read-out read-tsv recurse reduce regress-with reify relation reload
syn keyword waterBuiltin remove-last! render replace replace-where resample resample-indices resample-indices-ext reset reshape resume retract reverse
syn keyword waterBuiltin roll rot round round-down round-up row-maxes row-means row-mins row-sums rows>dataset rows>relation rshift
syn keyword waterBuiltin run run-result running? sample sample-with-replacement sample-without-replacement save save-image save-tsv se second see
syn keyword waterBuiltin see-compiled see-compiled>string see-tree see-tree>string see>string seed segment>pointer segment? select-columns select-keys select-rows select-values
syn keyword waterBuiltin set set-add! set-remove! set? shift shift-with shuffle side-depth side-drop side-peek sigmoid sin
syn keyword waterBuiltin size skip sleep slice! sort sort-by spaces split sq sqrt start-generator start-process
syn keyword waterBuiltin std stderr stdin stdout stop stream? string>chars string>codepoints string>number string>symbol string? submatrix
syn keyword waterBuiltin substring sum summary swap symbol? take tan tanh test test-report that this
syn keyword waterBuiltin throw time>iso timed to-slice! transpose trim true truncate try-catch tsv>db type-of union
syn keyword waterBuiltin unit unit-of update-at values var variables vars vector vf* vf+ vf- vf/
syn keyword waterBuiltin vfabs vfcos vfexp vflog vfneg vfsin vfsq vfsqrt vftan vftanh vstack vvf*
syn keyword waterBuiltin vvf*+ vvf*- vvf+ vvf- vvf/ wait wall-now water where wildcard? with-db with-intercept
syn keyword waterBuiltin with-stream words write write-file write-in write-tsv xml-escape xt? yield

hi def link waterComment      Comment
hi def link waterString       String
hi def link waterNumber       Number
hi def link waterSymbol       Constant
hi def link waterPath         Constant
hi def link waterFrameOp      Operator
hi def link waterFrameKey     Type
hi def link waterDefine       Define
hi def link waterDefName      Function
hi def link waterConditional  Conditional
hi def link waterRepeat       Repeat
hi def link waterKeyword      Keyword
hi def link waterLogic        Special
hi def link waterBoolean      Boolean
hi def link waterDelimiter    Delimiter
hi def link waterBuiltin      Statement
hi def link waterFormat       SpecialChar

let b:current_syntax = "water"
