#!/usr/bin/env python3
"""Render the runnable documentation examples into golden-test inputs.

Two kinds of runnable documentation, both extracted here:

1. Program fences — a block tagged exactly ``forth`` (README's taste
   block). Its blank-line-delimited sections become one golden input;
   a section calling load-library routes to tests/lib/ (external
   dependencies, run by make test-libs):

     tests/154_readme_taste.h2o          (make test; committed .expected)
     tests/lib/154_readme_taste_fit.h2o  (make test-libs; committed .expected)

   The .expected files are committed goldens, regenerated deliberately
   and inspected line by line:
     ./water -b < tests/154_readme_taste.h2o > tests/154_readme_taste.expected
     ./water tests/lib/154_readme_taste_fit.h2o \\
         > tests/lib/154_readme_taste_fit.expected
   tests/154_readme_taste.sed (hand-written, committed) normalizes the
   wall-now timestamp before run.sh diffs.

2. Example fences — a ``forth <word>`` fence paired with an ``output``
   fence (docs/reference.md, docs/reference-libraries.md; the format
   contract is in gen-help.py). Each reference section with examples
   becomes one generated trio

     tests/900_docs_<section-slug>.{h2o,expected,sed}

   (tests/lib/ for a section whose examples load the dependency-bearing
   statistics library; a pure-forth library section such as plotting
   stays in the core suite, per the tests convention). The .expected is
   the concatenated output fences — the reference's stated output IS
   the golden — and the .sed strips trailing blanks on both sides.
   The trios are fully generated and gitignored; stale ones from
   renamed sections are removed on every run. ``forth-noexec <word>``
   fences are help-only and never extracted. Example code must be
   self-contained (clear is inserted between pairs), deterministic
   (seed any random draw), and newline-terminated.
"""

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROGRAM_SOURCES = ["README.md", os.path.join("docs", "reference.md")]
EXAMPLE_SOURCES = [
    os.path.join("docs", "reference.md"),
    os.path.join("docs", "reference-libraries.md"),
]

MAIN_TEST = os.path.join("tests", "154_readme_taste.h2o")
LIB_TEST = os.path.join("tests", "lib", "154_readme_taste_fit.h2o")

FENCE = re.compile(r"^```(.*)$")
EXAMPLE_TAG = re.compile(r"^forth(-noexec)?\s+(\S+)\s*$")

GENERATED_HEADER = (
    "\\ generated by tools/gen-docs-tests.py from the runnable (```forth)\n"
    "\\ documentation fences -- edit the source document, not this file\n\n"
)

STRIP_TRAILING_BLANKS_SED = "s/[[:blank:]]+$//\n"


def slug(section_name):
    return re.sub(r"[^a-z0-9]+", "_", section_name.lower()).strip("_")


def parse_document(path):
    """Yield (kind, payload): kind 'program' -> fence text;
    kind 'example' -> (section, word, code, output)."""
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        lines = f.read().splitlines()

    events = []
    section = ""
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("## "):
            section = line[3:].strip()
            i += 1
            continue
        fence_line = FENCE.match(line)
        if not fence_line:
            i += 1
            continue
        info = fence_line.group(1).strip()
        body = []
        i += 1
        while i < len(lines) and lines[i] != "```":
            body.append(lines[i])
            i += 1
        if i >= len(lines):
            sys.stderr.write("error: %s: unterminated fence\n" % path)
            sys.exit(1)
        i += 1
        tag = EXAMPLE_TAG.match(info)
        if info == "forth":
            events.append(("program", "\n".join(body)))
        elif tag:
            noexec = tag.group(1) is not None
            word = tag.group(2)
            if i >= len(lines) or lines[i] != "```output":
                sys.stderr.write("error: %s: example for %r lacks its ```output fence\n"
                                 % (path, word))
                sys.exit(1)
            output = []
            i += 1
            while i < len(lines) and lines[i] != "```":
                output.append(lines[i])
                i += 1
            if i >= len(lines):
                sys.stderr.write("error: %s: unterminated output fence\n" % path)
                sys.exit(1)
            i += 1
            if not noexec:
                events.append(("example", (section, word, "\n".join(body), "\n".join(output))))
    return events


def program_sections(fence_text):
    parts = []
    current = []
    for line in fence_text.splitlines():
        if line.strip() == "":
            if current:
                parts.append(current)
                current = []
        else:
            current.append(line)
    if current:
        parts.append(current)
    return parts


def code_of(line):
    return line.split("\\", 1)[0]


def needs_library(section):
    return any("load-library" in code_of(line) for line in section)


def write_file(path, content):
    with open(os.path.join(ROOT, path), "w", encoding="utf-8") as f:
        f.write(content)


def emit_programs():
    main_sections = []
    lib_sections = []
    for source in PROGRAM_SOURCES:
        for kind, payload in parse_document(source):
            if kind != "program":
                continue
            for section in program_sections(payload):
                (lib_sections if needs_library(section) else main_sections).append(section)

    written = []
    for path, section_list in ((MAIN_TEST, main_sections), (LIB_TEST, lib_sections)):
        if not section_list:
            continue
        body = "\n\n".join("\n".join(section) for section in section_list)
        write_file(path, GENERATED_HEADER + body + "\n")
        written.append("%s (%d sections)" % (path, len(section_list)))
    return written


def emit_examples():
    for stale in glob.glob(os.path.join(ROOT, "tests", "9*_docs_*")) + \
            glob.glob(os.path.join(ROOT, "tests", "lib", "9*_docs_*")):
        os.remove(stale)

    grouped = {}
    order = []
    for source in EXAMPLE_SOURCES:
        if not os.path.exists(os.path.join(ROOT, source)):
            continue
        for kind, payload in parse_document(source):
            if kind != "example":
                continue
            section, _, code, output = payload
            if section not in grouped:
                grouped[section] = []
                order.append(section)
            grouped[section].append((code, output))

    written = []
    for section in order:
        pairs = grouped[section]
        external = any('"statistics" load-library' in code_of(line)
                       for code, _ in pairs for line in code.splitlines())
        test_dir = os.path.join("tests", "lib") if external else "tests"
        name = "900_docs_%s" % slug(section)
        base = os.path.join(test_dir, name)
        write_file(base + ".h2o",
                   GENERATED_HEADER + "\nclear\n".join(code + "\n" for code, _ in pairs))
        write_file(base + ".expected",
                   "".join(output + "\n" for _, output in pairs))
        write_file(base + ".sed", STRIP_TRAILING_BLANKS_SED)
        written.append("%s (%d examples)" % (base + ".h2o", len(pairs)))
    return written


def main():
    written = emit_programs() + emit_examples()
    print("wrote " + ", ".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
