#!/usr/bin/env python3
"""Render the runnable documentation examples into golden-test inputs.

Two kinds of runnable documentation, both extracted here:

1. Program fences — a block tagged exactly ``forth`` (README's taste
   block). Its blank-line-delimited sections become one golden input;
   a section calling load-library routes to tests/lib/ (external
   dependencies, run by make test-libs):

     tests/090_readme_taste.telic          (make test; committed .expected)
     tests/lib/090_readme_taste_fit.telic  (make test-libs; committed .expected)

   The .expected files are committed goldens, regenerated deliberately
   and inspected line by line:
     ./telic -b < tests/090_readme_taste.telic > tests/090_readme_taste.expected
     ./telic tests/lib/090_readme_taste_fit.telic \\
         > tests/lib/090_readme_taste_fit.expected
   tests/090_readme_taste.sed (hand-written, committed) normalizes the
   wall-now timestamp before run.sh diffs.

2. Example fences — a ``forth <word>`` fence paired with an ``output``
   fence (docs/reference.md, docs/reference-libraries.md; the format
   contract is in gen-help.py). Each reference section with examples
   becomes one generated trio

     tests/900_docs_<section-slug>.{telic,expected,sed}

   (tests/lib/ for a section whose examples load the dependency-bearing
   statistics library; a pure-forth library section such as plotting
   stays in the core suite, per the tests convention). The .expected is
   the concatenated output fences — the reference's stated output IS
   the golden — and the .sed strips trailing blanks on both sides.
   The trios are fully generated and gitignored; stale ones from
   renamed sections are removed on every run. ``forth-noexec <word>``
   fences are help-only and never extracted. Example code must be
   self-contained (clear is inserted between pairs), deterministic
   (seed any random draw), and newline-terminated.

3. Explanatory-doc example fences — the same ``forth <label>`` /
   ``output`` pair format in DOC_EXAMPLE_SOURCES (the label is free
   text, not a reference word; gen-help never reads these files). All
   of one document's pairs become a single trio

     tests/901_docs_<doc-stem>.{telic,expected,sed}

   routed to tests/lib/ when any pair loads the statistics library. A
   bare ``forth`` fence in these documents is display-only (they are
   not program sources), so sketches and fragments stay untagged.
"""

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROGRAM_SOURCES = ["README.md", os.path.join("docs", "reference.md")]
EXAMPLE_SOURCES = [
    os.path.join("docs", "reference.md"),
    os.path.join("docs", "reference-libraries.md"),
]
DOC_EXAMPLE_SOURCES = [
    os.path.join("docs", "continuations.md"),
    os.path.join("docs", "logic.md"),
    os.path.join("docs", "regression.md"),
    os.path.join("docs", "idioms.md"),
]

MAIN_TEST = os.path.join("tests", "090_readme_taste.telic")
LIB_TEST = os.path.join("tests", "lib", "090_readme_taste_fit.telic")

FENCE = re.compile(r"^(\s*)```(.*)$")
EXAMPLE_TAG = re.compile(r"^forth(-noexec)?\s+(\S+)\s*$")

GENERATED_HEADER = (
    "\\ generated by tools/gen-docs-tests.py from the runnable (```forth)\n"
    "\\ documentation fences -- edit the source document, not this file\n\n"
)

STRIP_TRAILING_BLANKS_SED = "s/[[:blank:]]+$//\n"


def slug(section_name):
    return re.sub(r"[^a-z0-9]+", "_", section_name.lower()).strip("_")


def parse_document(path):
    """Yield (kind, payload): kind 'program' -> fence text;
    kind 'example' -> (section, word, code, output)."""
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        lines = f.read().splitlines()

    events = []
    section = ""
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("## "):
            section = line[3:].strip()
            i += 1
            continue
        fence_line = FENCE.match(line)
        if not fence_line:
            i += 1
            continue
        indent = fence_line.group(1)
        info = fence_line.group(2).strip()

        def read_fence_body(start):
            collected = []
            j = start
            while j < len(lines) and lines[j] != indent + "```":
                stripped = lines[j]
                if stripped.startswith(indent):
                    stripped = stripped[len(indent):]
                collected.append(stripped)
                j += 1
            if j >= len(lines):
                sys.stderr.write("error: %s: unterminated fence\n" % path)
                sys.exit(1)
            return collected, j + 1

        body, i = read_fence_body(i + 1)
        tag = EXAMPLE_TAG.match(info)
        if info == "forth" and not indent:
            events.append(("program", "\n".join(body)))
        elif tag:
            noexec = tag.group(1) is not None
            word = tag.group(2)
            if i >= len(lines) or lines[i] != indent + "```output":
                sys.stderr.write("error: %s: example for %r lacks its ```output fence\n"
                                 % (path, word))
                sys.exit(1)
            output, i = read_fence_body(i + 1)
            if not noexec:
                events.append(("example", (section, word, "\n".join(body), "\n".join(output))))
    return events


def program_sections(fence_text):
    parts = []
    current = []
    for line in fence_text.splitlines():
        if line.strip() == "":
            if current:
                parts.append(current)
                current = []
        else:
            current.append(line)
    if current:
        parts.append(current)
    return parts


def code_of(line):
    return line.split("\\", 1)[0]


def needs_library(section):
    return any("load-library" in code_of(line) for line in section)


def write_file(path, content):
    with open(os.path.join(ROOT, path), "w", encoding="utf-8") as f:
        f.write(content)


def emit_programs():
    main_sections = []
    lib_sections = []
    for source in PROGRAM_SOURCES:
        for kind, payload in parse_document(source):
            if kind != "program":
                continue
            for section in program_sections(payload):
                (lib_sections if needs_library(section) else main_sections).append(section)

    written = []
    for path, section_list in ((MAIN_TEST, main_sections), (LIB_TEST, lib_sections)):
        if not section_list:
            continue
        body = "\n\n".join("\n".join(section) for section in section_list)
        write_file(path, GENERATED_HEADER + body + "\n")
        written.append("%s (%d sections)" % (path, len(section_list)))
    return written


def emit_examples():
    for stale in glob.glob(os.path.join(ROOT, "tests", "9*_docs_*")) + \
            glob.glob(os.path.join(ROOT, "tests", "lib", "9*_docs_*")):
        os.remove(stale)

    grouped = {}
    order = []
    for source in EXAMPLE_SOURCES:
        if not os.path.exists(os.path.join(ROOT, source)):
            continue
        for kind, payload in parse_document(source):
            if kind != "example":
                continue
            section, _, code, output = payload
            key = ("900", section)
            if key not in grouped:
                grouped[key] = []
                order.append(key)
            grouped[key].append((code, output))

    for source in DOC_EXAMPLE_SOURCES:
        if not os.path.exists(os.path.join(ROOT, source)):
            continue
        stem = os.path.splitext(os.path.basename(source))[0]
        key = ("901", stem)
        for kind, payload in parse_document(source):
            if kind != "example":
                continue
            _, _, code, output = payload
            if key not in grouped:
                grouped[key] = []
                order.append(key)
            grouped[key].append((code, output))

    written = []
    for key in order:
        prefix, section = key
        pairs = grouped[key]
        external = any('"statistics" load-library' in code_of(line)
                       for code, _ in pairs for line in code.splitlines())
        test_dir = os.path.join("tests", "lib") if external else "tests"
        name = "%s_docs_%s" % (prefix, slug(section))
        base = os.path.join(test_dir, name)
        write_file(base + ".telic",
                   GENERATED_HEADER + "\nclear\n".join(code + "\n" for code, _ in pairs))
        write_file(base + ".expected",
                   "".join(output + "\n" for _, output in pairs))
        write_file(base + ".sed", STRIP_TRAILING_BLANKS_SED)
        written.append("%s (%d examples)" % (base + ".telic", len(pairs)))
    return written


def main():
    written = emit_programs() + emit_examples()
    print("wrote " + ", ".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
