#!/usr/bin/env python3
"""Generate the language pack: telic-pack.md and its llms.txt copy.

One concatenated file holding the whole language for a model's context
window: the README taste block, docs/reference.md
and docs/reference-libraries.md verbatim (word tables, tokenizer rules,
and the tested example pairs), and docs/idioms.md verbatim.

The generator counts tokens per section (chars/4) against TOKEN_TARGET
and fails naming every section's size when the total overflows.
Regeneration is byte-identical: the inputs are read verbatim and the
header carries the VERSION string, never a timestamp.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TOKEN_TARGET = 100_000

PACK_PATH = "telic-pack.md"
LLMS_PATH = "llms.txt"

FENCE = re.compile(r"^```(.*)$")


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        return f.read()


def version():
    header = read(os.path.join("src", "c", "telic.h"))
    match = re.search(r'#define VERSION "([^"]+)"', header)
    if not match:
        sys.stderr.write("error: VERSION not found in src/c/telic.h\n")
        sys.exit(1)
    return match.group(1)


def taste_fences(path):
    fences = []
    body = None
    for line in read(path).splitlines():
        fence_line = FENCE.match(line)
        if fence_line:
            info = fence_line.group(1).strip()
            if body is None and info == "forth":
                body = []
            elif body is not None:
                fences.append("\n".join(body))
                body = None
            continue
        if body is not None:
            body.append(line)
    if body is not None:
        sys.stderr.write("error: %s: unterminated fence\n" % path)
        sys.exit(1)
    return "\n\n".join(fences)


def tokens(text):
    return (len(text) + 3) // 4


def main():
    taste = taste_fences("README.md")
    sections = [
        ("A taste of the language",
         "Runnable Telic, from the README. Each line's trailing comment is "
         "its printed output.\n\n```forth\n" + taste + "\n```",
         "README.md"),
        ("Reference",
         read(os.path.join("docs", "reference.md")),
         "docs/reference.md"),
        ("Loadable-library reference",
         read(os.path.join("docs", "reference-libraries.md")),
         "docs/reference-libraries.md"),
        ("Idioms",
         read(os.path.join("docs", "idioms.md")),
         "docs/idioms.md"),
    ]

    header = (
        "# Telic %s — the language pack\n\n"
        "Generated by tools/gen-pack.py; do not edit. This one file holds the\n"
        "complete Telic language for use as model context: a runnable taste,\n"
        "the full reference for built-in and embedded words, the reference for\n"
        "the loadable libraries, and the idioms. Every example in the\n"
        "references and idioms is extracted and verified by the test suite;\n"
        "the stated output is the actual output.\n" % version()
    )

    sizes = [(title, tokens(content), source) for title, content, source in sections]
    total = tokens(header) + sum(size for _, size, _ in sizes)

    report = ", ".join("%s %d (%s)" % (title, size, source)
                       for title, size, source in sizes)
    if total > TOKEN_TARGET:
        sys.stderr.write("error: pack is %d tokens (target %d): %s\n"
                         % (total, TOKEN_TARGET, report))
        sys.exit(1)

    pack = header + "".join(
        "\n---\n\n# %s\n\n%s" % (title, content.rstrip("\n") + "\n")
        for title, content, _ in sections)

    for path in (PACK_PATH, LLMS_PATH):
        with open(os.path.join(ROOT, path), "w", encoding="utf-8") as f:
            f.write(pack)

    print("wrote %s and %s: %d tokens (target %d): %s"
          % (PACK_PATH, LLMS_PATH, total, TOKEN_TARGET, report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
