#!/usr/bin/env python3
"""Generate examples/spitfire/scotland-terrain.telic, the ground's height over
the Scottish map.

Maintainer tool, run by hand; the generated file is committed, so playing the
game needs no network. It uses the two other generators' functions: the
heights from tools/gen-norway-terrain.py's reader of the AWS Terrain Tiles
(Tilezen's Terrarium PNGs at zoom 9, made from EU-DEM, SRTM and, in England,
the Environment Agency's LIDAR; github.com/tilezen/joerd/blob/master/docs/attribution.md),
at the corners of two 800 m grids laid in the game's own frame, metres east
and north of 56 N 3.6 W by the azimuthal equidistant projection from there,
each corner's latitude and longitude from the projection's inverse: one over
the rectangle round tools/gen-spitfire-map.py's mainland box, 54.9-58.7 N,
5.2-1.3 W, one over the rectangle round its northern isles' box,
58.7-60.9 N, 3.5-0.6 W; heights below 0 (the sea) as 0, and the corners
inside Loch Lomond and Loch Ness (Natural Earth's outlines, as the map draws
them) as 0, so the lochs stay open as the sea does.

  python3 tools/gen-scotland-terrain.py
"""

import importlib.util
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "examples", "spitfire", "scotland-terrain.telic")
SPACING = 800.0
ZOOM = 9


def load(name):
    spec = importlib.util.spec_from_file_location(name.replace("-", "_"), os.path.join(ROOT, "tools", name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


terrain = load("gen-norway-terrain")
mapping = load("gen-spitfire-map")


def inside_ring(x, z, ring):
    crossings = False
    for (x0, z0), (x1, z1) in zip(ring, ring[1:] + ring[:1]):
        if (z0 > z) != (z1 > z) and x < x0 + (z - z0) * (x1 - x0) / (z1 - z0):
            crossings = not crossings
    return crossings


def grid_lines(name, box, rings):
    x_low, z_low, x_high, z_high = mapping.ground_frame([box])
    columns = int((x_high - x_low) / SPACING) + 1
    rows = int((z_high - z_low) / SPACING) + 1
    corners = [(x_low + c * SPACING, z_low + r * SPACING) for r in range(rows) for c in range(columns)]
    found = terrain.heights(ZOOM, [terrain.inverse_azimuthal(x, z) for x, z in corners])
    for index, (x, z) in enumerate(corners):
        if any(inside_ring(x, z, ring) for ring in rings):
            found[index] = 0.0
    south, west, north, east = box
    lines = [
        "",
        "\\ the ground's heights in metres over the rectangle round {}-{} N, {}-{} W, row by row".format(
            south, north, -west, -east),
        "\\ from the south, each row west to east and an array of its own, so no literal outgrows",
        "\\ the stack, its corners every {:.0f} m from the south-west corner; the sea and the lochs 0".format(SPACING),
        "{:.0f} constant {}-terrain-west".format(x_low, name),
        "{:.0f} constant {}-terrain-south".format(z_low, name),
        "{:.0f} constant {}-terrain-spacing".format(SPACING, name),
        "{} constant {}-terrain-columns".format(columns, name),
        "{} constant {}-terrain-rows".format(rows, name),
        "[",
    ]
    for r in range(rows):
        lines.append("  [ " + " ".join("{:.0f}".format(max(0.0, h)) for h in found[r * columns:(r + 1) * columns]) + " ]")
    lines.append("] flatten {0}-terrain-rows {0}-terrain-columns matrix constant {0}-terrain-heights".format(name))
    print(name, rows, "rows", columns, "columns", flush=True)
    return lines


def main():
    lochs = mapping.lomond_runs() + mapping.layer_runs("ne_10m_lakes", {"Loch Ness"})
    lines = [
        "\\ Spitfire: the ground's height over the Scottish map, generated by",
        "\\ tools/gen-scotland-terrain.py from the AWS Terrain Tiles (produced using Copernicus",
        "\\ data and information funded by the European Union - EU-DEM layers; SRTM data courtesy",
        "\\ of the U.S. Geological Survey; (c) Environment Agency copyright and/or database right",
        "\\ 2015) and Natural Earth's lochs (public domain); do not edit, re-run the script.",
        "\\ Metres east (x) and north (z) of 56 N 3.6 W by the azimuthal equidistant projection.",
    ]
    lines += grid_lines("scotland", mapping.MAINLAND_BOX, lochs)
    lines += grid_lines("isles", mapping.ISLES_BOX, [])
    with open(OUT, "w") as out:
        out.write("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
