#!/usr/bin/env python3
"""Generate src/c/x11_colors.h, the named-color table, from X.Org's rgb.txt.

Maintainer tool, run by hand: it fetches a pinned copy of rgb.txt and checks its
sha256, so the table changes only when this script does. The generated header
is committed, so the build needs no network.

The table holds the single-word names with no digit in them, lowercased —
`dodgerblue`, not `DodgerBlue`, `dodger blue` or `DodgerBlue1` — which is the
set CSS adopted from X11. Both builds compile it: format turns `{name}` into a
terminal color escape, print-at into a pen color, and `colors` exposes it to
telic as a frame.

  python3 tools/gen-colors.py
"""

import hashlib
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "c", "x11_colors.h")
URL = "https://gitlab.freedesktop.org/xorg/app/rgb/-/raw/master/rgb.txt"
SHA256 = "f8e3a7bea17acc0b91e6285c5d32001db27d84c4461c655afdbce9dbeb4fb6f0"


def fetch():
    with urllib.request.urlopen(URL, timeout=60) as response:
        body = response.read()
    got = hashlib.sha256(body).hexdigest()
    if got != SHA256:
        raise SystemExit("rgb.txt sha256 mismatch:\n  expected %s\n  got      %s" % (SHA256, got))
    return body.decode("latin-1")


def colors(text):
    seen = {}
    ordered = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("!"):
            continue
        parts = line.split(None, 3)
        if len(parts) < 4:
            continue
        red, green, blue, name = parts
        if " " in name or re.search(r"\d", name):
            continue
        key = name.lower()
        if key in seen:
            continue
        seen[key] = (int(red) << 16) | (int(green) << 8) | int(blue)
        ordered.append(key)
    return sorted((name, seen[name]) for name in ordered)


def main():
    table = colors(fetch())
    lines = [
        "// GENERATED by tools/gen-colors.py from X.Org rgb.txt — do not edit by hand.",
        "#ifndef TELIC_X11_COLORS_H",
        "#define TELIC_X11_COLORS_H",
        "",
        "typedef struct {",
        "\tconst char *name;",
        "\tunsigned int rgb;",
        "} NamedColor;",
        "",
        "static const NamedColor x11_colors[] = {",
    ]
    for name, rgb in table:
        lines.append('\t{ "%s", 0x%06x },' % (name, rgb))
    lines += [
        "};",
        "",
        "#define N_X11_COLORS ((int)(sizeof(x11_colors) / sizeof(x11_colors[0])))",
        "",
        "#endif",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print("wrote %d colors to %s" % (len(table), OUT))


if __name__ == "__main__":
    main()
