#!/usr/bin/env python3
"""Language-pack acceptance battery (RELEASE-PLAN.md, release mechanics).

Each task in tests/acceptance/ is a .prompt (the task statement) and a
.expected (the exact stdout the program must produce, generated by the
reference solution in the matching .h2o). A trial sends the pack plus one
prompt to the model, extracts the single code fence, runs it under water,
and compares byte for byte. Failures carry water's own error text, which
classifies them: an undefined word is an invented word, a stack or type
error is a contract the pack states but does not demonstrate.
"""

import argparse
import concurrent.futures
import os
import pathlib
import re
import subprocess
import sys

import anthropic

ROOT = pathlib.Path(__file__).resolve().parent.parent
TASK_DIR = ROOT / "tests" / "acceptance"
OUT_DIR = ROOT / "generated" / "acceptance"
PACK = ROOT / "water-pack.md"
WATER = ROOT / "water"

INSTRUCTIONS = """\
Write one complete Water program that performs the task below.

Answer with the program and nothing else: a single ```forth fenced block,
no prose before or after it, no commentary inside it beyond Water comments.
The program is run as a file by the water interpreter, and its printed
output is compared against an exact expected text, so print exactly what the
task asks for, in the order asked, and nothing more.

Task:

"""

FENCE = re.compile(r"```(?:forth|water)?[^\n]*\n(.*?)```", re.DOTALL)


def extract_program(reply):
    fences = FENCE.findall(reply)
    if fences:
        return max(fences, key=len)
    return reply


def run_program(source, path):
    path.write_text(source if source.endswith("\n") else source + "\n")
    try:
        done = subprocess.run(
            [str(WATER), "-b", str(path)],
            capture_output=True,
            text=True,
            timeout=60,
        )
    except subprocess.TimeoutExpired:
        return "", "timed out after 60s", 1
    return done.stdout, done.stderr.strip(), done.returncode


def fingerprint(stderr, matched):
    if matched:
        return "pass"
    if not stderr:
        return "wrong-output"
    text = stderr.lower()
    if "unknown word" in text or "undefined" in text:
        return "invented-word"
    if "stack" in text:
        return "stack-shape"
    if "expected" in text or "type" in text:
        return "wrong-type"
    return "runtime-error"


class Battery:
    def __init__(self, args):
        self.args = args
        self.client = anthropic.Anthropic()
        self.pack = PACK.read_text() if not args.no_pack else None
        self.system = None
        if self.pack:
            self.system = [{
                "type": "text",
                "text": self.pack,
                "cache_control": {"type": "ephemeral"},
            }]
        self.usage = {"write": 0, "read": 0, "input": 0, "output": 0}
        self.arm_dir = OUT_DIR / ("nopack" if args.no_pack else "pack")
        self.arm_dir.mkdir(parents=True, exist_ok=True)

    def ask(self, messages):
        request = {
            "model": self.args.model,
            "max_tokens": 16000,
            "messages": messages,
        }
        if self.system:
            request["system"] = self.system
        with self.client.messages.stream(**request) as stream:
            message = stream.get_final_message()
        use = message.usage
        self.usage["write"] += use.cache_creation_input_tokens or 0
        self.usage["read"] += use.cache_read_input_tokens or 0
        self.usage["input"] += use.input_tokens or 0
        self.usage["output"] += use.output_tokens or 0
        return "".join(b.text for b in message.content if b.type == "text")

    def trial(self, task, sample):
        prompt = (TASK_DIR / f"{task}.prompt").read_text()
        expected = (TASK_DIR / f"{task}.expected").read_text()
        messages = [{"role": "user", "content": INSTRUCTIONS + prompt}]

        reply = self.ask(messages)
        program = extract_program(reply)
        path = self.arm_dir / f"{task}.s{sample}.h2o"
        stdout, stderr, code = run_program(program, path)
        matched = stdout == expected
        result = {
            "task": task,
            "sample": sample,
            "pass": matched,
            "fingerprint": fingerprint(stderr, matched),
            "stderr": stderr,
            "stdout": stdout,
            "repaired": False,
        }
        if matched or not self.args.repair:
            return result

        complaint = stderr if stderr else (
            f"The program ran but printed:\n{stdout}\nExpected:\n{expected}")
        messages += [
            {"role": "assistant", "content": reply},
            {"role": "user", "content":
                f"That program did not work. water reported:\n\n{complaint}\n\n"
                "Answer with a corrected complete program in one ```forth "
                "fence, nothing else."},
        ]
        reply = self.ask(messages)
        program = extract_program(reply)
        path = self.arm_dir / f"{task}.s{sample}.repair.h2o"
        stdout, stderr, code = run_program(program, path)
        result["repaired"] = stdout == expected
        return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="claude-opus-5")
    parser.add_argument("--samples", type=int, default=3)
    parser.add_argument("--tasks", default="*")
    parser.add_argument("--no-pack", action="store_true",
                        help="control arm: no pack in context")
    parser.add_argument("--repair", action="store_true",
                        help="one repair round per failing trial")
    parser.add_argument("--workers", type=int, default=6)
    args = parser.parse_args()

    if not WATER.exists():
        sys.exit("water binary not built; run make")
    if not PACK.exists():
        sys.exit("water-pack.md missing; run make pack")
    if not os.environ.get("ANTHROPIC_API_KEY"):
        sys.exit("ANTHROPIC_API_KEY not set")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    tasks = sorted(p.stem for p in TASK_DIR.glob(f"{args.tasks}.prompt"))
    if not tasks:
        sys.exit(f"no tasks matching {args.tasks}")

    battery = Battery(args)
    trials = [(t, s) for t in tasks for s in range(args.samples)]
    print(f"{len(trials)} trials over {len(tasks)} tasks, model {args.model}"
          f"{', no pack' if args.no_pack else ''}", flush=True)

    results = []
    # One trial alone first, so the pack is written to the cache once rather
    # than by every worker racing on a cold cache.
    results.append(battery.trial(*trials[0]))
    print(f"  {results[0]['task']} s{results[0]['sample']}: "
          f"{results[0]['fingerprint']}", flush=True)

    with concurrent.futures.ThreadPoolExecutor(args.workers) as pool:
        futures = {pool.submit(battery.trial, t, s): (t, s)
                   for t, s in trials[1:]}
        for future in concurrent.futures.as_completed(futures):
            task, sample = futures[future]
            try:
                result = future.result()
            except Exception as error:
                result = {"task": task, "sample": sample, "pass": False,
                          "fingerprint": "api-error", "stderr": str(error),
                          "stdout": "", "repaired": False}
            results.append(result)
            print(f"  {result['task']} s{result['sample']}: "
                  f"{result['fingerprint']}", flush=True)

    report(args, tasks, results, battery.usage)


def report(args, tasks, results, usage):
    passed = sum(1 for r in results if r["pass"])
    repaired = sum(1 for r in results if r["repaired"])
    lines = ["# Acceptance battery", ""]
    lines.append(f"- model: `{args.model}`")
    lines.append(f"- arm: {'no pack (control)' if args.no_pack else 'pack'}")
    lines.append(f"- trials: {len(results)} "
                 f"({len(tasks)} tasks x {args.samples} samples)")
    lines.append(f"- pass@1: {passed}/{len(results)}")
    if args.repair:
        lines.append(f"- recovered in one repair round: {repaired}")
    lines.append(f"- tokens: {usage['write']} cache-write, "
                 f"{usage['read']} cache-read, {usage['input']} input, "
                 f"{usage['output']} output")
    lines += ["", "| task | passes | fingerprints |", "|---|---|---|"]
    for task in tasks:
        own = [r for r in results if r["task"] == task]
        marks = sorted({r["fingerprint"] for r in own if not r["pass"]})
        lines.append(f"| {task} | {sum(1 for r in own if r['pass'])}"
                     f"/{len(own)} | {', '.join(marks) or '—'} |")
    failures = [r for r in results if not r["pass"]]
    if failures:
        lines += ["", "## Failures", ""]
        for r in failures:
            lines.append(f"### {r['task']} s{r['sample']} "
                         f"({r['fingerprint']})")
            lines.append("```")
            lines.append(r["stderr"] or r["stdout"] or "(no output)")
            lines.append("```")
            lines.append("")
    summary = "\n".join(lines) + "\n"
    name = "summary-nopack.md" if args.no_pack else "summary.md"
    (OUT_DIR / name).write_text(summary)
    print(f"\npass@1 {passed}/{len(results)} — {OUT_DIR / name}")


if __name__ == "__main__":
    main()
